version: '3'

volumes:
  data:
services:
  plus_unit:
    build:
      context: a-plus
      dockerfile: .github/workflows/Dockerfile
    volumes:
      - ./a-plus:/a-plus
    working_dir: /a-plus
    environment:
      - APLUS_BASE_URL="-"
    command: python3 manage.py test
  plus_selenium:
    build:
      context: a-plus
      dockerfile: .github/workflows/Dockerfile
    volumes:
      - ./a-plus:/a-plus
#    ports: # these can be used for debugging
#      - "5680:5678"
#      - "8001:8001"
#      - "8889:8889"
    working_dir: /a-plus
    command: selenium_test/run_servers_and_tests.sh